---
# https://github.com/ouster-lidar/ouster-ros/blob/ros2/README.md#overview
  - ros_topic_name: <robot_namespace><component_name>/ouster/points
    gz_topic_name: <robot_namespace><component_name>/ouster/points/points
    ros_type_name: sensor_msgs/msg/PointCloud2
    gz_type_name: gz.msgs.PointCloudPacked
    lazy: true
    direction: GZ_TO_ROS
